### ISSUE TITLE
not find the rosaria package 

### ISSUE THREAD

**Issue by TWSTYPH** [Lkaho/Online-Motion-Planning-based-on-Bezier#1]
May ask why the rosaria package is included in the start.launch, but it is not found in your repository?
![2023-05-18 17-49-50屏幕截图](https://github.com/Lkaho/Online-Motion-Planning-based-on-Bezier/assets/103561103/48729713-c413-4f02-8970-5c94cc53aa42)

**Comment by Lkaho** [comment]
Hi, rosaria is a package for my robot.  You can ignore it and send the publish commands to your robot.
